name = "Tracy"
uuid = "e689c965-62c8-4b79-b2c5-8359227902fd"
authors = ["Cody Tapscott <cody.tapscott@juliahub.com>", "Kristoffer Carlsson <kristoffer.carlsson@juliahub.com>"]
version = "0.1.4"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
LibTracyClient_jll = "ad6e5548-8b26-5c9f-8ef3-ef0ad883f3a5"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[weakdeps]
TracyProfiler_jll = "0c351ed6-8a68-550e-8b79-de6f926da83c"

[compat]
ExprTools = "0.1"
julia = "1.11"

[extensions]
TracyProfilerExt = "TracyProfiler_jll"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TracyProfiler_jll = "0c351ed6-8a68-550e-8b79-de6f926da83c"

[targets]
test = ["Pkg", "Test", "TracyProfiler_jll"]
